### ISSUE TITLE
Add ability to change port for indexer [feature request]

### ISSUE THREAD

**Issue by vovapyc** [brumik/obsidian-ollama-chat#11]
I had problems running indexer because it runs on 5000 port and it's already used by AirPlay receiver on macOS (https://www.reddit.com/r/perl/comments/10p8p39/macos_port_5000_mystery_solved/#:~:text=Recent%20versions%20of%20macOS%20have,AirPlay%2C%22%20it%20says%20here.). It would be nice to be able to change indexer URL in settings

**Comment by brumik** [comment]
This is an issue for the other porject, and this is already possible, you can customize it in the .env file as per readme: https://github.com/brumik/ollama-obsidian-indexer/blob/main/ollama_obsidian_indexer/.env.sample

I hope this helps ^^

**Comment by n0012** [comment]
The settings tab in Obsidian Ollama Chat won't appear unless it successfully communicate with the indexer service (skipping initialization error message).  This is problematic if port 5000 is already in use by another service, such as Airplay receiver.

Please update the Obsidian Ollama Chat to show the settings tab regardless of indexer communication status.

I solved by:
1) turning off Airplay Receiver (Apple menu > System Settings >General. Then click AirDrop & Handoff. Disable AirPlay Receiver.
2) Running Indexer on Port 5000
3) Open Obsidian, which now exposes Setting tab for Ollama Chat plugin
4) Change LlamaIndex Connector URL to http://localhost:5001
5) Change Indexer docker port to Port 5001 and relaunch
6) Reopen Obsidan
7) Re-enable Airplay Receiver

**Comment by brumik** [comment]
I see, sorry, it was not clear what is the issue, so the fact that settings is not showing up is the problem. I am on hollidays but in 2 weeks I will fix this

**Comment by brumik** [comment]
Hey, sorry, forgot about this issue, is this still needing a fix? I can work on it this weekend if so.

**Comment by brumik** [comment]
https://github.com/brumik/obsidian-ollama-chat/releases/tag/0.1.4 in this version this issue should be fixed
