### ISSUE TITLE
"Error while indexing the store Error: Request failed, status 500"

### ISSUE THREAD

**Issue by ReaderGuy42** [brumik/obsidian-ollama-chat#12]
I just installed the python indexer, and according to `docker ps` it's running:
```
982a8ba328   ollama-obsidian-indexer:latest   "poetry run python -…"   9 minutes ago   Up 9 minutes   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   ollama-obsidian-indexer-main-indexer-1
```

I then installed the plugin in Obsidian and I keep getting this error:

![image](https://github.com/user-attachments/assets/18195722-205e-48e9-990e-706faebab207)

this error appears in my test vault with only a single note of three lines, and the error appears anytime the vault saves, I guess. On boot the top part about indexing appears, but there's not really much to index.

I can open the modal, but I don't think that'll load till the error is resolved. I modified `.env` in the indexer 
```
APP_DEVELOPMENT=0
APP_PORT=5000
OLLAMA_BASE_URL="http://127.0.0.1:11434"
LLM_MODEL="tinyllama"
LLM_TEMPERATURE=0.1
OLLAMA_EMBED_MODEL_NAME="nomic-embed-text"
LLM_PROMPT_TEMPLATE="
<s>[INST]
You are a helpful assistant, you will use the provided context to answer user questions.
Read the given context before answering questions and think step by step. If you can not answer a user question based on 
the provided context, inform the user. Do not use any other information for answering user. Provide a detailed answer to the question.

Context: {context_str}
User: {query_str}
[/INST]
"
INDEXES_PERSIST_DIR="./storage"
NOTES_BASE_PATH="/home/Obsidian/samplevault"
```

besides the path, I also changed the embed_model and model name because I didn't have the default ones installed. My Linux Mint laptop is not very strong as far as LLM power goes, but Tinyllama is pretty fast when run in terminal, so it should also run normally in Obsidian.

Any help appreciated!
Thanks :)

**Comment by brumik** [comment]
Hello, could you send me the logs from the Python service running?

**Comment by ReaderGuy42** [comment]
How do I get the logs? I'm running the script via Docker, right?

**Comment by brumik** [comment]
If you have docker desktop you should be able to see the logs from there. From terminal you can https://docs.docker.com/reference/cli/docker/container/logs/ or you can just simply attach to the container and see it as it is happening: https://docs.docker.com/reference/cli/docker/container/attach/

**Comment by ReaderGuy42** [comment]
Thanks!

```
docker container logs ollama-obsidian-indexer-main-indexer-1 
 * Serving Flask app 'ollama_obsidian_indexer.server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 724-922-266
 * Serving Flask app 'ollama_obsidian_indexer.server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.18.0.2:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 682-451-829
```

**Comment by brumik** [comment]
Can you post if there is something when you open ollama and you get the error you originally posted. Also these logs do not look like they have you .env file settings applied.

**Comment by ReaderGuy42** [comment]
I'll close this for now, as I'm not sure Ollama is for me. Thanks though!
