### ISSUE TITLE
How can a non coder use this?

### ISSUE THREAD

**Issue by Gourav1910** [brumik/obsidian-ollama-chat#3]
Is there some step by step instructions available for a non coder to set this up?

**Comment by brumik** [comment]
I am working on the backend part, shoud be similar in the end how ollama works in the end. As I am doing this in my free time please be patient. I hope end of January I will have something that is easy to set up with documentation.

Though you will need at least a basic understanding of docker and file system paths.

**Comment by brumik** [comment]
I updated the python part: https://github.com/brumik/ollama-obsidian-indexer

It is not good yet, but usable if you can run python scripts, any feedback welcome :)
