### ISSUE TITLE
missing main.js

### ISSUE THREAD

**Issue by cryptonaut01** [brumik/obsidian-ollama-chat#6]
Tried to import the plugin to obsidian, but receive the following error:
```
app.js:1 
Plugin failure: ollama-chat Error: ENOENT: no such file or directory, open '.../.obsidian/plugins/obsidian-ollama-chat/main.js'
```
Seems the Repo does not contain the missing file. Do I miss anything ?

**Comment by brumik** [comment]
Hey, how did you installed the plugin? Recommended method is to install it from the official plugin store. If you just pulled the release.zip or the github repo you need to build the main.js yourself with `npm run build` (https://github.com/brumik/obsidian-ollama-chat/blob/main/package.json#L8) but for this you need dependecies like `node`.

Official pulgin link: https://obsidian.md/plugins?id=ollama-chat

**Comment by cryptonaut01** [comment]
Thx for the hint. That was a quick one. Build it by my own. Was not aware that the plugin is available as well via the community store. Might be worth mentioning it in the readme.

**Comment by cryptonaut01** [comment]
Thx for the hint. That was a quick one. Build it by my own. Was not aware that the plugin is available as well via the community store. Might be worth mentioning it in the readme.

**Comment by brumik** [comment]
Already added it when seen the question :D Maybe I am forgetful but at least realize my mistakes fast :D. Happy to help, and good luck using it
