### ISSUE TITLE
Suggestion: Notification every time indexing occurs is a bit much

### ISSUE THREAD

**Issue by tcarwash** [brumik/obsidian-ollama-chat#8]
I'm not sure how hard it is to add a config entry for notification verbosity, but that would be awesome. 

I deleted this line in my install:
https://github.com/brumik/obsidian-ollama-chat/blob/60c61795aef1e7df1b551a03eece47ea9f0d796e/src/Ollama.ts#L61

so I only get popups for indexing errors instead of every time I type something.

**Comment by brumik** [comment]
Good point, on mobile I see it bit annoying. I will look into making it optional.

**Comment by brumik** [comment]
Released in: https://github.com/brumik/obsidian-ollama-chat/releases/tag/0.1.1
